### ISSUE TITLE
Using both `--show-accessed` and `--show-unaccessed` with the `file` command only outputs unaccessed fields

### ISSUE THREAD

**Issue by Aloshi** [untergeek/es-fieldusage#2]
[This line](https://github.com/untergeek/es-fieldusage/blob/main/src/es_fieldusage/commands.py#L159-L160) opens in `'w'` mode, which clobbers the first half of the file written in the first iteration of the for loop. Changing this to:

```py
                with open(filename, 'a', encoding='utf-8') as fdesc:
```

Fixes it. You could also `os.remove` the file at the start of the outer for to keep the old "overwrite if exists" behavior.

**Comment by untergeek** [comment]
Fixed by #4
